Adds src/regression_test/test_prep_release_metadata_regression.py CLI for prep_release_metadata
Fixes an AttributeError: 'PosixPath' object has no attribute 'os' in src/crn_utils/asap_ids.py

* Removes unused table.stem code in src/crn_utils/release_util.py